name: this is my githubaction
on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: welcome message
          run: echo " hey prem clear the interview for senior devops engineer role "

        - name: list the file
          run: ls -a

        - name: read file
          run: cat README.md

        - name: create a file
          run: touch txt.1
